global:
  scrape_interval: 15s
scrape_configs:
- job_name: vllm
  metrics_path: /metrics
  file_sd_configs:
  - files:
    - /etc/prometheus/targets.json
- job_name: litellm-gateway
  metrics_path: /metrics
  static_configs:
  - targets:
    - vllm-gateway:4000
    labels:
      instance: spark.local
- job_name: monitoring
  static_configs:
  - targets:
    - cadvisor:8080
    - node-exporter:9100
    - dcgm-exporter:9400
    - vector:9102
    labels:
      instance: spark.local
  metric_relabel_configs:
  - source_labels:
    - __name__
    regex: DCGM_FI_DEV_XID_ERRORS
    action: drop
- job_name: home_local
  file_sd_configs:
  - files:
    - /prometheus/home_local.json
  relabel_configs:
  - target_label: instance
    replacement: home.local
- job_name: blackbox
  metrics_path: /probe
  params:
    module:
    - http_2xx
  static_configs:
  - targets:
    - https://c.jlapenna.net
    - https://m.jlapenna.net
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter:9115
