import asyncio
import os
import sys
from pathlib import Path

import yaml
from loguru import logger

from sparkstack.core.env import SPARKRUN_CMD, is_monitoring_external
from sparkstack.core.utils import async_run_command, async_run_compose


def _extract_hostname(target: str) -> str:
    """Return the bare hostname from an SSH target string.

    Handles ``ssh://user@host``, ``user@host``, and bare ``host``.
    """
    t = target.replace("ssh://", "")
    if "@" in t:
        t = t.split("@", 1)[1]
    return t.split(":")[0]


async def _deploy_remote_infrastructure(
    stack: dict,
    stack_dir: Path,
) -> None:
    """Deploy Tailscale sidecars and resolve Tailnet IPs for remote backends.

    Implements the two-phase remote infrastructure setup described in the
    multi-node plan (Step 2, Phases 1-2):

    1. Deploy head sidecar (if not running).
    2. Deploy one worker sidecar per unique remote host.
    3. Resolve Tailnet IPs for each sidecar.
    4. Write ``.state.json`` with the resolved IPs.
    5. Trigger a config rebuild so LiteLLM gets the correct ``backend_url``s.

    Args:
        stack: Parsed ``stack.yaml`` dict.
        stack_dir: Path to the active stack directory.
    """
    from sparkstack.core.builders.stack import StackBuilder  # noqa: PLC0415
    from sparkstack.core.env import (  # noqa: PLC0415
        SPARKSTACK_HEADSCALE_AUTH_KEY,
        get_headscale_url,
        is_overlay_configured,
    )
    from sparkstack.manager.remote import (  # noqa: PLC0415
        deploy_head_sidecar,
        deploy_worker_sidecar,
        resolve_worker_tailnet_ip,
        sidecar_name,
        write_sidecar_state,
    )

    if not is_overlay_configured():
        logger.warning(
            "Remote backends found but SPARKSTACK_HEADSCALE_SERVER is not set. "
            "Sidecars will not be deployed; backends may fail to connect."
        )
        return

    auth_key = SPARKSTACK_HEADSCALE_AUTH_KEY
    headscale_url = get_headscale_url()

    if not auth_key:
        raise RuntimeError(
            "Remote backends require SPARKSTACK_HEADSCALE_AUTH_KEY. "
            "Run 'sparkstack setup overlay' first."
        )

    # Phase 1: Deploy head sidecar.
    logger.info("🔗 Deploying head sidecar...")
    await deploy_head_sidecar()

    # Collect unique remote hosts.
    remote_backends = [b for b in stack.get("backends", []) if b.get("is_remote")]
    unique_hosts: dict[str, str] = {}  # hostname → raw_target
    for backend in remote_backends:
        raw = backend.get("target", "")
        if raw:
            hostname = _extract_hostname(raw)
            unique_hosts[hostname] = raw

    # Phase 1 (cont): Deploy worker sidecars for unique remote hosts.
    for hostname, raw_target in unique_hosts.items():
        logger.info(f"🔗 Deploying worker sidecar on '{hostname}' ({raw_target})...")
        await deploy_worker_sidecar(raw_target, hostname, auth_key, headscale_url)

    # Phase 2: Resolve Tailnet IPs.
    sidecars: dict = {}
    for hostname, raw_target in unique_hosts.items():
        logger.info(f"📡 Resolving Tailnet IP for '{hostname}'...")
        ip = await resolve_worker_tailnet_ip(raw_target, hostname)
        sidecars[hostname] = {
            "container_name": sidecar_name(hostname),
            "tailnet_ip": ip,
            "role": "worker",
        }
        logger.info(f"  📍 {hostname} → {ip}")

    # Write state so the config rebuild can pick up the IPs.
    cluster_name = stack.get("cluster_name", "")
    write_sidecar_state(stack_dir, cluster_name, sidecars)
    logger.info("💾 Sidecar state written to .state.json")

    # Phase 3 (config): Rebuild configs now that IPs are known.
    # rebuild_from_stack reads .state.json → populates LiteLLM backend_urls
    # with Tailnet IPs and monitoring targets with Tailnet IPs.
    logger.info("🔄 Rebuilding stack configs with resolved Tailnet IPs...")
    await StackBuilder.rebuild_from_stack(stack_dir)


async def launch_stack(
    stack_dir: Path, *, rebuild_images: bool = False, env: dict[str, str] | None = None
) -> None:
    repo_root = Path(__file__).parent.parent.parent.resolve()
    stack_yaml_path = stack_dir / "stack.yaml"

    if not stack_yaml_path.exists():
        logger.error(f"❌ Error: {stack_yaml_path} not found.")
        raise FileNotFoundError(f"{stack_yaml_path} not found.")

    with open(stack_yaml_path) as f:
        stack = yaml.safe_load(f)

    # --- Remote infrastructure: sidecars + IP resolution ---
    # Must happen before backend teardown (we need IPs in the new config),
    # and before backend launch (sidecars must exist for network_mode to work).
    remote_backends = [b for b in stack.get("backends", []) if b.get("is_remote")]
    if remote_backends:
        await _deploy_remote_infrastructure(stack, stack_dir)
        # Reload stack.yaml — it may have been regenerated by the config rebuild.
        with open(stack_yaml_path) as f:
            stack = yaml.safe_load(f)

    # --- Tier 1 teardown: stop sparkrun-managed backends on remote hosts ---
    from sparkstack.manager.remote import read_sidecar_state  # noqa: PLC0415

    state = read_sidecar_state(stack_dir)
    cluster_name = state.get("cluster_name", "")
    if cluster_name:
        logger.info(f"🧹 Stopping remote sparkrun backends (cluster: {cluster_name})...")
        try:
            await async_run_command(
                [*SPARKRUN_CMD, "stop", "--all", "--cluster", cluster_name],
                check=False,
                capture_output=True,
                env=env,
            )
        except Exception as e:
            logger.warning(f"sparkrun stop --all failed (non-fatal): {e}")

    # --- Soft launch: remove stale local backend containers ---
    logger.info("🧹 Removing stale local backend containers...")
    try:
        result = await async_run_command(
            ["docker", "ps", "-aq", "--filter", "label=sparkstack-backend=true"],
            check=False,
            capture_output=True,
            env=env,
        )
        stale_containers = result.stdout.strip().split() if result.stdout else []
        if stale_containers:
            await async_run_command(
                ["docker", "rm", "-f"] + stale_containers,
                check=False,
                env=env,
            )
    except Exception as e:
        logger.warning(f"Failed to query or remove stale backends: {e}")

    # --- Launch backends via sparkrun ---
    logger.info("🚀 Launching model instances via sparkrun...")
    global_network = "sparkstack-net"

    for backend in stack.get("backends", []):
        recipe = backend["recipe"]
        if recipe.startswith("@"):
            recipe_path = recipe
        else:
            recipe_path = repo_root / "sparkstack-registry" / recipe

        raw_target = backend.get("target", "localhost")
        is_remote = backend.get("is_remote", False)

        if is_remote:
            # Remote: sparkrun SSHes to the LAN hostname to launch the backend.
            hosts_value = raw_target
            hostname = _extract_hostname(raw_target)
            logger.info(
                f"  🌐 Backend '{backend['name']}' → remote host '{hostname}' ({raw_target})"
            )
        else:
            hosts_value = "localhost"

        cmd = [
            "uv",
            "run",
            "sparkrun",
            "run",
            str(recipe_path),
            "--hosts",
            hosts_value,
            "--port",
            str(backend.get("port", 8000)),
            "--tp",
            str(backend.get("tensor_parallel", 1)),
            "--served-model-name",
            backend["name"],
            "--cluster",
            backend["name"],
            "--container-name",
            backend["name"],
            "--no-follow",
            "--label",
            "sparkstack-backend=true",
        ]

        # Network injection: remote backends join the pre-deployed sidecar's
        # network namespace; local backends join the shared Docker bridge.
        if is_remote:
            from sparkstack.manager.remote import sidecar_name  # noqa: PLC0415

            hostname = _extract_hostname(raw_target)
            cmd.extend(["-o", f"network=container:{sidecar_name(hostname)}"])
            # Override OTEL endpoint to reach Alloy/Prometheus via the Tailnet.
            head_ip = os.getenv("SPARKSTACK_HEAD_TAILNET_IP", "")
            if head_ip:
                cmd.extend(["-o", f"env.OTEL_EXPORTER_OTLP_ENDPOINT=http://{head_ip}:4318"])
        else:
            cmd.extend(["-o", f"network={global_network}"])

        if rebuild_images:
            cmd.append("--rebuild")

        if "memory_limit" in backend:
            cmd.extend(["--memory-limit", backend["memory_limit"]])

        # Append overrides.
        overrides = backend.get("overrides", {}).copy()

        # Pull out explicit flags if present in overrides.
        if "gpu_memory_utilization" in overrides:
            cmd.extend(["--gpu-mem", str(overrides.pop("gpu_memory_utilization"))])
        if "max_model_len" in overrides:
            cmd.extend(["--max-model-len", str(overrides.pop("max_model_len"))])

        for key, value in overrides.items():
            cmd.extend(["-o", f"{key}={value}"])

        # Append environment variables.
        for key, value in backend.get("env", {}).items():
            cmd.extend(["-o", f"env.{key}={value}"])

        for lbl in backend.get("labels", []):
            cmd.extend(["--label", lbl])

        await async_run_command(cmd, cwd=repo_root, stream_output=True, env=env)

    # --- Launch compose services (gateway + monitoring) ---
    external = is_monitoring_external()
    if external:
        logger.info("📦 Starting gateway + monitoring agents (external mode) via docker compose...")
    else:
        logger.info("📦 Starting gateway and monitoring via docker compose...")

    compose_file = "docker-compose.yaml"
    compose_args = ["-f", str(stack_dir / compose_file)]

    monitoring_dir = repo_root / "services" / "monitoring"
    if external:
        compose_args.extend(["-f", str(monitoring_dir / "docker-compose.external.yml")])

    await async_run_compose(
        stack_dir,
        *compose_args,
        "up",
        "-d",
        "--build",
        project_root=repo_root,
        project_name="current",
        env=env,
    )
    logger.info("✅ Stack is operational.")


async def main():
    if len(sys.argv) < 2:
        print("❌ Error: stack directory not provided.")
        sys.exit(1)

    stack_dir = Path(sys.argv[1]).resolve()
    await launch_stack(stack_dir)


if __name__ == "__main__":
    asyncio.run(main())
