global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
- job_name: vllm-inference
  static_configs:
  - targets:
    - researcher:8000
    - embedding:8000
    - whisper:8000
- job_name: litellm-gateway
  static_configs:
  - targets:
    - litellm:4000
- job_name: monitoring
  static_configs:
  - targets:
    - cadvisor:8080
    - node-exporter:9100
    - nv-monitor:9101
    - tempo:3200
    - vector:9102
